######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 8 00:41:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . old
INCLUDEPATH += . old

# Input
HEADERS += temple.h graph.h
SOURCES += temple.cpp graph.cpp

QT += opengl
