######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 8 00:41:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += 
INCLUDEPATH += 

# Input
HEADERS += temple.h graph.h lang.h
SOURCES += temple.cpp graph.cpp lang.cpp

QT += opengl
